name: CI â€” Lint, Jest & NodeBB Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  jest-and-nodebb-tests:
    name: CI Tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8.0.1
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Solved Plugin
        run: npm install ./nodebb-plugin-solved

      - name: Install Anonymous Button Plugin
        run: npm install ./nodebb-plugin-anonymous-button

      - name: Setup on Redis
        run: |
          node app --setup="{}" --ci="{}"

      - name: âœ… Run Jest Tests
        run: npm test

      - name: ğŸ” Coverage
        run: npm run coverage

      - name: âœ… Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
